#!/usr/bin/env bash
#ddev-generated

## Description: Start OpenCode server.
## Usage: opencode-serve
## Example: ddev opencode-serve
## MutagenSync: true

~/.opencode/bin/opencode serve --port=4096 --hostname=0.0.0.0
